<?php

namespace Plugin\SendLogReport\Repository;

use Doctrine\ORM\EntityRepository;
use Eccube\Application;
use Plugin\SendLogReport\Entity\SendLogReportConfig;

/**
 * SendLogReportConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendLogReportConfigRepository extends EntityRepository
{

    public $cacheKey = 'send_log_report_config';

    /**
     * @var \Eccube\Application
     */
    protected $app;

    public function setApplication(Application $app)
    {
        $this->app = $app;
    }

    public function get($id = 1)
    {
        $options = $this->app['config']['doctrine_cache'];
        $lifetime = $options['result_cache']['lifetime'];

        $query = $this->createQueryBuilder('s')
            ->where('s.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        $query->useResultCache(true, $lifetime, $this->cacheKey);

        return $query->getOneOrNullResult();
    }

    public function save(SendLogReportConfig $SendLogReportConfig)
    {

        $em = $this->getEntityManager();

        // IDは1固定
        $SendLogReportConfig->setId(1);

        // ログ除外対象
        $logSelect = json_encode(array_values($SendLogReportConfig->getLogSelect()));
        $SendLogReportConfig->setLogSelect($logSelect);

        $em->persist($SendLogReportConfig);
        $em->flush($SendLogReportConfig);

        $em->getConfiguration()->getResultCacheImpl()->delete($this->cacheKey);
    }
}
